name: Auto PullRequest
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: CSS lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: CSS lint with stylelint
      uses: actions-hub/stylelint@master
      env:        
        PATTERN: "**/*.css"
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: trstringer,acdunnigan
      - name: Deploy to production
        run: echo deploying